package com.crafts.profileservice.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.*;

import java.util.List;
import java.util.Map;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "user_profile")
public class UserProfile {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String userId;

    @DynamoDBAttribute
    private BusinessProfile businessProfile;

    @DynamoDBAttribute
    private String consolidatedStatus;

    @DynamoDBAttribute
    private List<String> subscriptions;

}


